name: CI - Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cruddb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d cruddb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t flask-crud-app .

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U user && break
            echo "Postgres not ready yet..."
            sleep 5
          done

      - name: Run Flask container
        run: |
          docker run -d --name flask-app \
            -e DATABASE_URL=postgresql://user:password@localhost:5432/cruddb \
            -p 5000:5000 flask-crud-app
